### ISSUE TITLE
Crash NSInvalidArgumentException

### ISSUE THREAD

**Issue by RodolfoGS** [merryjs/photo-viewer#102]
Hi, I have a crash _randomly_ on iOS (production). I can see that crashes in Crashlytics but I can't reproduce it in my device.

```
Fatal Exception: NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]
```

![image](https://user-images.githubusercontent.com/870365/71363799-e7d77780-255f-11ea-8124-5ebad5026916.png)

Any suggestion that what happen?
Maybe is a network issue. I don't know if is this issue, is only a suggestion, any idea?

---
react-native: 0.61.4
@merryjs/photo-viewer: 3.1.1
Platform: iOS
Devices: 13.1.3 iPhone 7, 13.3.0 iPhone 6s Plus, 13.1.2 iPhone XS Max, etc...

**Comment by bang88** [comment]
@RodolfoGS Sorry about that. Maybe its a network issue I guess.

**Comment by RodolfoGS** [comment]
@bang88 I created a PR with the fix, I'm using in production and works perfect. I added a validation to verify that the current photo is not nil.

PR: https://github.com/merryjs/photo-viewer/pull/104
