### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by bang88** [merryjs/photo-viewer#11]
- [x] IOS
- [x] Android blocked by https://github.com/stfalcon-studio/FrescoImageViewer/issues/57 have to fork it then fixes this issue

**Comment by bang88** [comment]
next version

**Comment by bang88** [comment]
![jul-30-2017 17-26-51](https://user-images.githubusercontent.com/433259/28752654-0073ffe8-754f-11e7-9e37-688ac55876af.gif)

**Comment by tikkichan4** [comment]
Is it support GIF on IOS now ? 
This is the best react native photo viewer but gif support is quite important for me....
Thanks a lot !

**Comment by bang88** [comment]
Not yet. 😢

**Comment by zhouanbo** [comment]
I came across a library https://github.com/DylanVann/react-native-fast-image that uses [SDWebImage](https://github.com/rs/SDWebImage) to show GIF in iOS, not sure if it will be of any help.

**Comment by bang88** [comment]
> @bang88 I came across a library https://github.com/DylanVann/react-native-fast-image that uses [SDWebImage](https://github.com/rs/SDWebImage) to show GIF in iOS, not sure if it will be of any help.

Actually if we use SDWebImage for load image then it should working. But now I am use `react-native` Image loader so that we can support multiple formats at once except gif. 😃
