### ISSUE TITLE
Framework not found NYTPhotoViewer

### ISSUE THREAD

**Issue by wulaizi** [merryjs/photo-viewer#124]
Hey, this dependency is not friendly to lower versions of rn at all
Installation is too troublesome 0.58.6, an error was reported
Framework not found NYTPhotoViewer

**Comment by bang88** [comment]
@wulaizi Yep.  you need upgrade your RN to a close version.

**Comment by wulaizi** [comment]
> @wulaizi Yep. you need upgrade your RN to a close version.
There are too many things involved

**Comment by wulaizi** [comment]
> > @wulaizi Yep. you need upgrade your RN to a close version.
> > There are too many things involved

0.58.6 Can't it be used？？？
