### ISSUE TITLE
w/o native dependencies

### ISSUE THREAD

**Issue by geirman** [merryjs/photo-viewer#13]
this looks great, but is it possible to do it without native dependencies? Could see it being useful as part of an Expo app.

**Comment by bang88** [comment]
I am afraid not, its a native warpper. Can't use this with EXPO. Thanks

**Comment by geirman** [comment]
Yeah, I was thinking this functionality might be achieved purely in JavaScript, without the native wrapper. Then it would be more portable. Have you thought about it?

**Comment by bang88** [comment]
No, this is not a javascript version, so can not be portable. if you want to work with expo it must be a pure javascript implementation.

**Comment by geirman** [comment]
I know it isn't right now. I'm obviously not communicating clearly, but I'm wondering if you'd consider refactoring the native dependencies out so that it were a pure js implementation.

**Comment by bang88** [comment]
I am sorry for that, it can not be that way,This package are more focus on performance if you really need a pure javascript version,
Maybe you can try this one https://github.com/ascoders/react-native-image-viewer.

**Comment by geirman** [comment]
Cool, that makes sense. Maybe add that to your readme then so people know why they might choose one over the other
