### ISSUE TITLE
Progress bar for ios

### ISSUE THREAD

**Issue by bang88** [merryjs/photo-viewer#14]

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/28956617-7b02d7b4-7920-11e7-9b8d-43fddcf6d07a.png)

I hope progress bar like this...

**Comment by bang88** [comment]
I have try to implement a progress bar like this, not done yet.

**Comment by musicode** [comment]
@bang88 我猜你是中国人，非常感谢开源这个库，我等了一年半，终于有人做了，RN 其他大图浏览库都是渣

**Comment by bang88** [comment]
你好 😄

**Comment by musicode** [comment]
有几个改进建议：

1. 是否可以支持 tap 之后 dismiss，这样就不需要左上角放一个关闭按钮
2. 是否可以在图片数量少时，支持多个小圆点的 indicator，或者让外部自己配置，因为调用方知道图片的数量，自己选择要 `current/total` 还是小圆点风格
3. 右上角的按钮是否可以改为长按手势呢？因为还没运行起来，不知长按是否有啥特殊用途

**Comment by bang88** [comment]
1. Tap 估计目前不行，iOS 实现用的是 NYT的，但是现在支持Swipe dismiss 基本够用，实现的时候也要考虑 iOS 跟 android
2. 这个应该可以实现
3. 有这个计划

第一个版本我是希望能够正常在项目里面使用起来，后面再慢慢完善。  二期计划改成 组件的形式调用，这样对于类似的需求会更方便配置一点。

你可以提 issues， 不过建议还是 英语的方式方便别人查看或者 有人可以PR。 如果别人也遇到跟你一样的问题就方便回答了。

你本地运行不了的问题，再看下README 看看是不是什么地方没有设置好。

**Comment by musicode** [comment]
好的，主要是我英文略差，写这一大段太费脑子了，以后我尽量写英文。。

**Comment by bang88** [comment]
Progress bar maybe have issues due to NYT's implementation

**Comment by musicode** [comment]
@bang88 maybe you can see [PhotoBrowser](https://github.com/JiongXing/PhotoBrowser)

**Comment by bang88** [comment]
I understand this is what you want, but its not easy to implementation everything you want in both IOS and Android, I like some features of them provided, but can not copy to here and use it like normal. there have many limitations we can not do today.

If you really want a feature just like WeChat do, i recommend you try to wrap it by yourself. At first i want this library as simple as possible. 

Thanks.

**Comment by musicode** [comment]
I just need an component support zoom and drag and writed by native.

no matter what you choose, I will use this component.

**Comment by musicode** [comment]
抱歉再次用中文，因为与此项目无关，我想问下你是否对富文本编辑器有需求呢
