### ISSUE TITLE
Component 'MerryPhotoView' re-registered direct event 'topDismiss' as a bubbling event

### ISSUE THREAD

**Issue by zhigang1992** [merryjs/photo-viewer#142]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/1057756/166860605-8993ee06-070e-4907-bc7e-01d90cdb3e96.png">

This happens on react-native 0.68 any ideas?

**Comment by zhigang1992** [comment]
https://github.com/react-native-video/react-native-video/pull/1625/files

**Comment by zhigang1992** [comment]
https://github.com/facebook/react-native/pull/32355

**Comment by zhigang1992** [comment]
I fixed it by renaming onDismiss and onChange completely to `onImageViewDismiss` and `onImageViewChange`

**Comment by bang88** [comment]
@zhigang1992 Could you send a PR please ?

**Comment by RodolfoGS** [comment]
@bang88 I created a PR, feel free to try it

**Comment by bang88** [comment]
@RodolfoGS 3.2.5 just released. Thank you.
