### ISSUE TITLE
how to pass the onDismiss callback?

### ISSUE THREAD

**Issue by musicode** [merryjs/photo-viewer#22]
I show call `show()` with `hideStatusBar: true`，I hope to showStatusBar after dismiss.

**Comment by bang88** [comment]
This feature has done on `next` branch.  will add it into `2.0.0`.

**Comment by musicode** [comment]
when to release `2.0.0` ?

**Comment by bang88** [comment]
Maybe  1 - 2 weeks.

**Comment by bang88** [comment]
@musicode #24  Please give it a try.

**Comment by musicode** [comment]
give you a hug
