### ISSUE TITLE
2.0.0 beta is out

### ISSUE THREAD

**Issue by bang88** [merryjs/photo-viewer#24]
See  https://github.com/merryjs/photo-viewer/blob/next/README.md#usage

**Comment by musicode** [comment]
support image in photo library?

**Comment by bang88** [comment]
#21

**Comment by musicode** [comment]
can't install 2.0

```
npm install @merryjs/photo-viewer@2.0.0 --save
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @merryjs/photo-viewer@2.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

if I use `npm install @merryjs/photo-viewer --save`, the `1.0.0` is installed

**Comment by bang88** [comment]
Not release yet, is a beta version, but no worry, I am refactoring for support local images, and api have a braking change. Will release ASAP.

**Comment by musicode** [comment]
write by component maybe is not a good choise.

because photo view is a fullscreen component, I can't define any element, like `Enter` button or `Skip` Button for a guide screen. and photo view is so common, I have to write so many code to switch `visible` prop, it is boring.

**Comment by musicode** [comment]
If a screen need a header, like below:

```
<View>
    <Header />
    <PhotoView />
</View>
```

this is usefull, but for other cases, call native method is more convenience.

**Comment by bang88** [comment]
I have a few thoughts. using Component just like function so don't worry.

**Comment by musicode** [comment]
waiting for 2.0 release.

**Comment by bang88** [comment]
Using Component so we can remove Android Activity. and some style resources.

**Comment by bang88** [comment]
For better support local images , I have to refactor the logics ios and android. but now seems working in my dev env. but ios have a limitation no support gif. I have file an issue in rn repo but no response till now.

**Comment by bang88** [comment]
Needs more tests.

but you can install the beta version `npm i @merryjs/photo-viewer@2.0.0-beta.3`

and then checkout the example file. https://github.com/merryjs/photo-viewer/blob/refactor-image-loader/example/photos.js#L25

**Comment by musicode** [comment]
thanks, `using Component just like function so don't worry.`  how to write like function?
