### ISSUE TITLE
iOS: App crashes when trying to save image

### ISSUE THREAD

**Issue by longsangstan** [merryjs/photo-viewer#27]
The app crashes when I try to save an image.

Steps to reproduce: Click the icon on the right hand corner -> save image -> crashes. 

Other actions (e.g. Mail, Copy) seem to work fine.

Btw, this is the best photo-viewer for RN so far!

**Comment by bang88** [comment]
@longsangstan  Hey you need add a key to info.plist, Apple needs it.
```xml
<key>NSPhotoLibraryUsageDescription</key>
<string>Add your descriptions here .</string>
```

**Comment by longsangstan** [comment]
Thanks! Problem solved.

**Comment by simonemarinelli** [comment]
Update:
in XCode 9 the key has changed to:

```
<key>NSPhotoLibraryAddUsageDescription</key> 
<string>Save image to Camera Roll</string>
```

Thanks for this awesome Photo Viewer!
