### ISSUE TITLE
IOS crash when I run in my iphone with release mode

### ISSUE THREAD

**Issue by musicode** [merryjs/photo-viewer#30]
- react-native v0.51.0
- xcode v9.2

- iOS

Run in my iPhone with release mode, crash

Run in Simulator with release mode, it is ok

**Comment by musicode** [comment]
@bang88 do you have time to fix it?

**Comment by bang88** [comment]
@musicode could you check the device logs and put it here. I can not reproduce it.

**Comment by musicode** [comment]
sorry, it is my fault.

by the way, do you have plan to wrap other native lib for react native?
