### ISSUE TITLE
Add support for custom pagination / tab / navbar

### ISSUE THREAD

**Issue by tikkichan4** [merryjs/photo-viewer#32]
The module is now have enough functionality, but it seems having a leak of customization supporting. It should be excellent if we can customize pagination , tab bar or nav bar for the photo viewer.

**Comment by marospekarik** [comment]
+1 , this is the only package I found here that's working properly, great job! Would really appreciate customization options for a header content

**Comment by bang88** [comment]
Which kind of customization of header component ?

**Comment by marcoizzo** [comment]
+1

**Comment by Stmol** [comment]
+1 I t a tried ton of open source image galleries, but only this one works without any obvious problems. The only thing missing here for this type of projects is the ability to customize own View components on a slider layout.

**Comment by bang88** [comment]
> But as I understand, this could not be achieved without changing the original NYTPhotoViewer

You totally right. But PR are always welcome
