### ISSUE TITLE
Close button for android

### ISSUE THREAD

**Issue by marospekarik** [merryjs/photo-viewer#33]
I'm not able to see a close button on android device

**Comment by CrazyPython** [comment]
You have to swipe down instead.

**Comment by bang88** [comment]
I think this is unnecessary for android platform. always using the physical back button simple and easy to do.

**Comment by rogchap** [comment]
Not all Android devices have physical back buttons, hence Google introducing back arrow into Material Design.

**Comment by CrazyPython** [comment]
@rogchap Swiping down without a close button is a common pattern on Android. The system teaches this to you when Android is first launched.

**Comment by rogchap** [comment]
When UX is involved it's not always down to the paradims of a platform that matter, but what users expect or are familiar with. 

Sometimes it's also about accessibility: in our case we have visually impaired / blind users as well as an older generation that are not familiar to technology. These people use the back button in the top left, and teaching another way just for one screen is not so easy. 

A configurable back button that is consistent with iOS makes sense.

**Comment by CrazyPython** [comment]
Android users expect the back button to work. It might be confusing to you if you come from iOS, but if you look at Android Google Photos, that's what it does. People expect the UI to be consistent across photo viewers.
