### ISSUE TITLE
Does not support iPhone X

### ISSUE THREAD

**Issue by simonemarinelli** [merryjs/photo-viewer#40]

**Comment by bang88** [comment]
Does it crashes or something else ?

**Comment by simonemarinelli** [comment]
No crashes.
It's only a graphic problem.
I attach 2 images below.

![landscape](https://user-images.githubusercontent.com/14885349/35907985-bc1f7420-0bef-11e8-95c8-68ea589ac7c9.jpeg)
![portrait](https://user-images.githubusercontent.com/14885349/35907986-bc418b96-0bef-11e8-9fea-dabdb2ca74f7.jpeg)

**Comment by bang88** [comment]
The issue is come from NYT PhotoViewer should fixed in upstream.

**Comment by CrazyPython** [comment]
@bang88 It seems like NYTPhotoViewer has been updated and on cocoapods https://github.com/NYTimes/NYTPhotoViewer/pull/249

**Comment by bang88** [comment]
@CrazyPython It seems problem are still there. not fixed

**Comment by CrazyPython** [comment]
Can you check again? Maybe update NYTPhotoViewer to 2.0.0

**Comment by bang88** [comment]
You can have a check I have upgrade to version 2.0.0 already

**Comment by simonemarinelli** [comment]
Same problem
