### ISSUE TITLE
clang: error: linker command failed with exit code 1 

### ISSUE THREAD

**Issue by belgajohnpauldimaano** [merryjs/photo-viewer#42]
framework not found FLAnimatedImage.

Can I ask for a help with this. I follow the documentation but I got the error.

**Comment by AbelYangGitHub** [comment]
Same issue, how can i fix this?

**Comment by CristianOspina** [comment]
In your `project.pbxproj` file search for `FRAMEWORK_SEARCH_PATHS` and add the folder where we have the new frameworks: `"$(SRCROOT)/../node_modules/@merryjs/photo-viewer/ios/Carthage/Build/iOS/"` (you have to do that for each search result, two in my case)

It should look like this:
```
FRAMEWORK_SEARCH_PATHS = (
  "$(inherited)",
  "$(PROJECT_DIR)",
  "$(SRCROOT)/../node_modules/@merryjs/photo-viewer/ios/Carthage/Build/iOS/",
);
```

After that it should work, following all the normal steps that are in the README.

**Comment by belgajohnpauldimaano** [comment]
I forgot some configuration in xcode. I fixed in my machine by following the instructions for IOS.

**Comment by bohdan145** [comment]
I've got the same problem
But i can't find FRAMEWORK_SEARCH_PATHS in my .pbxproj file
