### ISSUE TITLE
Adding support for lazy loading more photos

### ISSUE THREAD

**Issue by ankitladhania** [merryjs/photo-viewer#43]
I have an experimental photo app which has hundreds of photos, its not possible for me to bring all of them in first render.

Can we add support for adding more photos dynamically, I see that `onNavigateToPhoto` was added but has been commented out, any specific reason for this?

Love your library, thanks.

**Comment by bang88** [comment]
@ankitladhania Are you have troubles when loading too many photos. AFAIK it will load only one photo at a moment. and load another one after you navigate to it.

**Comment by ankitladhania** [comment]
But still its not optimal to get 500 photos from the server in one go, so I would like to break it into multiple backend calls. Thus, requiring the feature to lazy load more photos
