### ISSUE TITLE
Android activity is not found

### ISSUE THREAD

**Issue by musicode** [merryjs/photo-viewer#44]
```
<activity
        android:name="com.merryjs.PhotoViewer.PhotoViewer.MerryPhotoViewActivity"
        android:theme="@style/Theme.Transparent" />
```

where is `MerryPhotoViewActivity`? so that compile is not work

![image](https://user-images.githubusercontent.com/2732303/37142068-ed097112-22f1-11e8-9848-1b0fc19be4b0.png)

**Comment by musicode** [comment]
@bang88

**Comment by musicode** [comment]
![image](https://user-images.githubusercontent.com/2732303/37160509-5b77a0ea-232b-11e8-9707-c162f1efa6aa.png)
@bang88 how to resolve it, it make me painful

**Comment by krvajal** [comment]
For some reason the activity tag is been placed outside the application tag in the manifiest, which seems really weired to me

**Comment by krvajal** [comment]
@musicode if you look a this   `android:name="com.merryjs.PhotoViewer.PhotoViewer.MerryPhotoViewActivity`
you will see that the package name is incorrect as it has `PhotoViewer.PhotoViewer` twice and it should appear only once.

**Comment by bang88** [comment]
@krvajal 👍 

@musicode  Are you upgrade your gradle tools?

**Comment by musicode** [comment]
yes, my gradle is 3.0.1

**Comment by bang88** [comment]
@musicode Does this https://github.com/merryjs/photo-viewer/issues/44#issuecomment-372734208 can help you ? I don't recommend upgrade gradle since React Native still use a lower version.

**Comment by musicode** [comment]
I have try a js component, because I want to custom the photo view with some buttons.

I don't want to spend time on compile error, i dont know what happened.

thank you.
