### ISSUE TITLE
Android Gradle 4.0.1 - Unable to find module with Gradle path

### ISSUE THREAD

**Issue by kevinkevw** [merryjs/photo-viewer#46]
Build is ok, however it shows the below error message when do Gradle sync:
Error:Unable to find module with Gradle path ':@merryjs/photo-viewer' (needed by module 'app'.)

I tried to remove the "@" but it still couldn't sync.

**Comment by bang88** [comment]
@kevinkevw Can you check #39 does solve your problem. I haven't upgrade Gradle yet.
