### ISSUE TITLE
How to keep track of slide changes?

### ISSUE THREAD

**Issue by RSSfeed** [merryjs/photo-viewer#47]
is there a way to track a slide change (i.e. `onChange`)? Like e.g. `onDismiss` gives the option to catch when viewer has been dismissed.

**Comment by bang88** [comment]
@RSSfeed Sorry. have no such events now. can you explain where you need this events.

**Comment by RSSfeed** [comment]
is there a possibility to add such an event?
I need it to sync the image carousel. There is an image carousel showing cropped images, once pressed PhotoViewer shows up (with full version of images). When changing index within PhotoView, the carousel below should update according.

**Comment by bang88** [comment]
Maybe will implement it in the future. would you like give it a try ?

**Comment by RSSfeed** [comment]
that'll be awesome :)
what do you mean, me trying to create a PR? I can try, but my native knowledge is limited..

but doesn't this line here trigger the event to react native (commented out)? https://github.com/merryjs/photo-viewer/blob/243b7c9c6af7f93c8fa5e585eeaba30acc118393/ios/MerryPhotoViewManager.m#L28

**Comment by bang88** [comment]
Yep.

**Comment by RSSfeed** [comment]
So why have those been commented out? Has there been an issue?

**Comment by bang88** [comment]
Because this feature are useless and yes its a WIP feature. not complete yet.

**Comment by RSSfeed** [comment]
I understand, I'll be patient. Thanks for your help 👍
