### ISSUE TITLE
Opening 2 instances when visible

### ISSUE THREAD

**Issue by zhouanbo** [merryjs/photo-viewer#49]
Hi @bang88 ,

Thanks for the library, I'm liking it a lot! 

When I try it in my project, I observed a weird behavior that the viewer instance is opening 2 instances of itself. Because when I dismiss it using swipe gesture, there's another one in the background showing the same picture. And it then disappear because of the onDismiss function. If I remove the onDismiss function, I'll have to swipe twice to dismiss it. 

My code looks roughly like this, I also checked that I only have one <PhotoView /> in the project:

```javascript
{/** Pics */ }
<View style={{ flexGrow: 1, marginLeft: 5 + 49 + 5, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', width: 85 * 2 + 5 }}>
  <PhotoView
    visible={this.state.visible}
    data={this.state.photos}
    hideStatusBar={true}
    initial={this.state.initial}
    onDismiss={e => {
      //this.setState({ photos: [], visible: false });
    }}
  />
  {rowData.pics ? rowData.pics.map((pic, idx) => {
    return <TouchableOpacity key={rowID + idx} onPress={() => this.setState({ visible: true, initial: idx, photos: rowData.pics.map(image => { return { source: { uri: image } } }) })}>
        <View style={{ backgroundColor: '#f4f4f4', alignSelf: 'flex-start', marginTop: 10, width: 85, height: 85 }}>
          <CachedImage key={rowData.id} style={{ width: 85, height: 85 }} source={{ uri: pic}} />
        </View>
    </TouchableOpacity>
  }) : null}
</View>
```

If you could help me with this, it'll be more than appreciated!

**Comment by bang88** [comment]
>  onDismiss={e => {
       this.setState({ visible: false });
    }}

Glad you enjoy it. but you need reset state after it dismissed

**Comment by zhouanbo** [comment]
Thanks for the lightening response! Yes, I did it in the actual code, I commented that for the debugging purposes, and find out it might have 2 instances opening by doing that because I need to swipe twice to dismiss it :( I'll make two gifs to show it, I'm making them right now..

**Comment by zhouanbo** [comment]
This is the behavior if I commented onDismiss:
![video1](https://user-images.githubusercontent.com/4448810/38008286-ddbb7c58-321b-11e8-9aad-73bee8b96c9b.gif)
I needed to swipe by myself twice to dismiss it.

This is the behavior I leave the onDismiss:
![video2](https://user-images.githubusercontent.com/4448810/38008434-a7b47c4e-321c-11e8-9092-2398b08e563d.gif)
I only needed to swipe once, but there's a background behind which I suppose it's the second instance.

**Comment by bang88** [comment]
Its weird. when you reset the state the PhotoViewer will re-render. It should not have two instances. Do you taped twice? or something I can't reproduce it on my side. we have use this library a few months.

**Comment by zhouanbo** [comment]
Hmm, thanks for the information. At least I know it's me specific. I'll try to look further into it.

**Comment by zhouanbo** [comment]
Hi @bang88 ,
I found out the reason for the problem, it's because I put it inside a ListView so maybe it's loop a few times, once I move it out it's good.

Again, thanks for this awesome library!
