### ISSUE TITLE
IOS Example

### ISSUE THREAD

**Issue by bang88** [merryjs/photo-viewer#5]

**Comment by bang88** [comment]
https://github.com/merryjs/examples

**Comment by musicode** [comment]
我用过你写的 photo-viewer，知道 ios 是通过 framework 的方式集成的第三方库，最近我在用 swift 写一些东西，并且希望集成进 RN，swift 我是以 framework 的方式用 Carthage 发布，我感觉跟 photo-viewer 好像挺类似，想借鉴，不知可否指教一下呢
