### ISSUE TITLE
hideShareButton and hideCloseButton props not working

### ISSUE THREAD

**Issue by kevinkevw** [merryjs/photo-viewer#53]
Referring to the document ( https://merryjs.github.io/photo-viewer/interfaces/merryphotoviewporps.html ), both hideShareButton and hideCloseButton are not working on Android.

Moreover, if the source paths are local, the Share function on Android doesn't work like expected, it will be sharing just the file:// path, which is not accessible from outside the app.

[Wishlist] Is it possible to add a "Save" button? 😄

**Comment by bang88** [comment]
![image](https://user-images.githubusercontent.com/433259/39391524-3c0f0b3e-4ad7-11e8-8848-7a260b945bd6.png)
![image](https://user-images.githubusercontent.com/433259/39391525-3c9bbc64-4ad7-11e8-9dc3-0801d28fbe93.png)

hideShareButton and hideCloseButton props works as expected. Please check the example for more informations
