### ISSUE TITLE
How to set a 'original thumbnail' position, to trigger from and dismiss to?

### ISSUE THREAD

**Issue by samfriend** [merryjs/photo-viewer#54]
How to set a 'original thumbnail' position, to trigger from and dismiss to, like the animated gif example on https://github.com/NYTimes/NYTPhotoViewer

how to let the photo-viewer has a effects that pops / trigger from a thumbnail

and when swipe-up-dismiss, it will 'shrink / roll back' to the the 'original' size (the thumbnail)?

thanks

**Comment by bang88** [comment]
NYT's example needs a reference of Image but can not provided via React Native.
