### ISSUE TITLE
Can you open or share the way to customize overlay information.

### ISSUE THREAD

**Issue by vietnd87** [merryjs/photo-viewer#56]
Hi there,

I'm newbie in RN and I found your library very helpful. But some time I want to have some functionality in bottom of overlay photo view ex: comment, download buttons also only one double tab zoom level...

If you can open some input for overlay view example: header, footer (RN component input as well) of each picture. So I can modify anything in there with your onChange event.

Thank you!

**Comment by bang88** [comment]
@vietnd87 to be honest I don't know how to add React Component into Native view for now. 

IOS side you can long press the image it will open up a system share window you can save image or share it.
