### ISSUE TITLE
Data not update with stage change

### ISSUE THREAD

**Issue by vietnd87** [merryjs/photo-viewer#61]
I tried to reload new data but it not update, It seem keep the first data render. Can you advise how to reload  data for this component?

**Comment by vietnd87** [comment]
Here is my simple render code in a component:

`render() {
console.log(this.props.photos);
return (
  <View>
    <PhotoView
      visible={this.props.visible}
      data={this.props.photos}
      hideStatusBar={false}
      hideShareButton
      initial={0}
      onDismiss={this.props.onDismiss.bind(this)}
      onChange={this.onPhotoChange.bind(this)}
    />
  </View>
  )
}`

When I change photos props from main screen to this component I see in console log the change (added more photos) but data in PhotoView not change.

**Comment by bang88** [comment]
The code looks fine. Can you checkout the example folder which have a simple example which works as expected. I can not tell whats the problem with your code here.

**Comment by vietnd87** [comment]
Ok, I will review my code again. Thank you!

**Comment by vietnd87** [comment]
My problem is other case here:

on first render the data as this: 

data = [
	{
	        source: {
			uri: picture.picture_url
		}
		title: '0 likes',
	}
]

Next props, we updated comment count in data:

data = [
	{
		source: {
			uri: picture.picture_url
		}
		title: '1 like',
	}
]

So, When the photo is showing and click like to update data it not be update immediately

**Comment by bang88** [comment]
This seems is an issue that the data not update after PhotoViewer has been opening.
Could you try it via https://facebook.github.io/react-native/docs/direct-manipulation
