### ISSUE TITLE
Build failed on ios (FLAnimatedImage error)

### ISSUE THREAD

**Issue by bohdan145** [merryjs/photo-viewer#62]
I've added embedded binaries(FLAnimatedImage, ) before build, but
I'm getting this error when try to build project:

ld: framework not found FLAnimatedImage
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by CristianOspina** [comment]
See a workaround here: https://github.com/merryjs/photo-viewer/issues/42#issuecomment-414210029

**Comment by bohdan145** [comment]
@CristianOspina  can't find FRAMEWORK_SEARCH_PATHS in my .pbxproj file (

**Comment by CristianOspina** [comment]
Make sure you have linked the package: `react-native link @merryjs/photo-viewer`

**Comment by bohdan145** [comment]
![default](https://user-images.githubusercontent.com/26411546/44386321-d8d75400-a52a-11e8-8807-5b65f5c539ce.png)

**Comment by bohdan145** [comment]
Can i change Search paths in Xcode not in file ?

**Comment by CristianOspina** [comment]
I guess, I don't know much about this, but I know the error is that it don't know where to look for the framework.

**Comment by CristianOspina** [comment]
@bohdan145 Try to add the path in Build Settings: https://i.stack.imgur.com/IYBV0.png for both Debug and Release.

**Comment by bohdan145** [comment]
@CristianOspina  Yeah, it helped)
Thanks a lot)
Buit i actually added 3 lines
![default](https://user-images.githubusercontent.com/26411546/44389449-8b131980-a533-11e8-8997-eb8f2f2bb493.png)
