### ISSUE TITLE
ios Installation issue

### ISSUE THREAD

**Issue by amitbravo** [merryjs/photo-viewer#64]
I am little confused about iOS installation , after automatic linking using react-native link @merryjs/photo-viewer , I see link 
pod ‘MerryPhotoViewer’, path: ‘../node_module/@merryjs/photo-viewer’ added to my podfile, should I now simply link frameworks and I good to go ? Should I really need to use ... :branch=> ‘master’ link in to my podfile ?

**Comment by bang88** [comment]
@amitbravo No. just use pod directly.
