### ISSUE TITLE
Android Build fails

### ISSUE THREAD

**Issue by bbeckk** [merryjs/photo-viewer#76]
```
error: bundling failed: Error: While resolving module `react-native/Libraries/Image/ImageSourcePropType`, the Haste package `react-native` was found. However the module `Libraries/Image/ImageSourcePropType` could not be found within the package. Indeed, none of these files exist:

  * `E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\react-native\Libraries\Image\ImageSourcePropType(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\react-native\Libraries\Image\ImageSourcePropType\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at resolveHasteName (E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\metro-resolver\src\resolve.js:229:9)
    at Object.resolve (E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\metro-resolver\src\resolve.js:92:20)
    at ModuleResolver.resolveDependency (E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:143:31)
    at ResolutionRequest.resolveDependency (E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\metro\src\node-haste\DependencyGraph.js:273:16)
    at Object.resolve (E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\metro\src\lib\transformHelpers.js:261:42)
    at dependencies.map.result (E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\metro\src\DeltaBundler\traverseDependencies.js:391:31)
    at Array.map (<anonymous>)
    at resolveDependencies (E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\metro\src\DeltaBundler\traverseDependencies.js:388:18)
    at E:\zreactNative\test\zzzProject\PhotoViewerForTest\node_modules\metro\src\DeltaBundler\traverseDependencies.js:261:33
 DELTA  [android, dev] ..\..\../index.js ▓▓▓▓▓▓▓▓▓▓▓░░░░░ 70.5% (465/554)::ffff:127.0.0.1 - - [13/Feb/2019:11:04:21 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
 DELTA  [android, dev] ..\..\../index.js ▓▓▓▓▓▓▓▓▓▓▓░░░░░ 70.5% (465/554), failed.
```

As soon as the following PhotoViewer.js is imported, the build fails

PhotoViewer.js

	class MerryPhotoView extends React.Component {
	  constructor() {
		super(...arguments);
		/**
		 * Handle UIColor conversions
		 * @param data Photo[]
		 */
		this.processor = data => {
		  if (data && data.length) {
			return data.map(o => {
			  const d = { ...o };
			  if (typeof o.summaryColor === "string") {
				d.summaryColor = processColor(o.summaryColor);
			  }
			  if (typeof o.titleColor === "string") {
				d.titleColor = processColor(o.titleColor);
			  }
			  if (!this.props.hideCloseButton) {
				console.log("falsezz*", this.props.visible);
				d.source = resolveAssetSource({
				  uri: baseUrl + `${o.restaurantPhotosPath}${o.file_name}`
				});
			  } else {
				console.log("truezz*", this.props.visible);
				d.source = resolveAssetSource({
				  uri: baseUrl + `${o.restaurantMenusPath}${o.file_name}`
				});
			  }

			  return d;
			});

		  }
		  return data;
		};
	  }

	  render() {
		// nothing
		if (this.props.visible === false) {
		  // console.log('falsezz*', this.props.visible);
		  return null;
		} else {
		  // console.log('truezz', this.props.visible);
		}

		const { visible, data, initial, ...props } = this.props;
		const dataCopy = [...data];
		const transformData = this.processor(dataCopy);
		console.log(props);
		// initial
		let startPosition = initial;
		if (initial < 0) {
		  startPosition = 0;
		}
		if (initial > dataCopy.length) {
		  startPosition = dataCopy.length;
		}
		return (
		  <RNMerryPhotoView
			{...props}
			initial={startPosition}
			data={transformData}
		  />
		);
	  }
	}
	MerryPhotoView.propTypes = {
	  data: PropTypes.arrayOf(
		PropTypes.shape({
		  source:
			Platform.OS === "ios"
			  ? ImageSourcePropType
			  : PropTypes.oneOfType([
				  PropTypes.shape({
					uri: PropTypes.string,
					headers: PropTypes.objectOf(PropTypes.string)
				  }),
				  // Opaque type returned by require('./image.jpg')
				  PropTypes.number,
				  // Multiple sources
				  PropTypes.arrayOf(
					PropTypes.shape({
					  uri: PropTypes.string,
					  width: PropTypes.number,
					  height: PropTypes.number
					})
				  )
				]),
		  title: PropTypes.string,
		  summary: PropTypes.string,
		  titleColor: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
		  summaryColor: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
		})
	  ).isRequired,
	  visible: PropTypes.bool,
	  initial: PropTypes.number.isRequired,
	  hideStatusBar: PropTypes.bool,
	  // IOS only
	  hideCloseButton: PropTypes.bool,
	  // IOS only
	  hideShareButton: PropTypes.bool,
	  onDismiss: PropTypes.func.isRequired,
	  onNavigateToPhoto: PropTypes.func,
	  shareText: PropTypes.string
	};
	MerryPhotoView.defaultProps = {
	  visible: false
	};
	export default MerryPhotoView;

**Comment by bang88** [comment]
Please use 3.0.0

**Comment by bbeckk** [comment]
I've used 3.0.0.

```
  "dependencies": {
    "@merryjs/photo-viewer": "^3.0.0",
    "react": "16.6.3",
    "react-native": "0.58.4"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
```

**Comment by bang88** [comment]
Please remove node_modules reinstall it try again. I created an empty project using the latest version react-native and photo-viewer and can not reproduce this issue.

**Comment by bbeckk** [comment]
The issue occurs as soon as the PhotoViewer.js is imported

import PhotoView from "./Photo-viewer"; 

P.S see the PhotoViewer.js above.

**Comment by bbeckk** [comment]
The issue occurs when the Photo-viewer.js is imported.

import PhotoView from "./PhotoViewer";

P.S Have a look at the PhotoViewer.js code above.

**Comment by bbeckk** [comment]
There is no ImageSourcePropType in latest project. Replaced it with ImageProps and it works fine
