### ISSUE TITLE
Warning: Failed prop type: checker is not a function.

### ISSUE THREAD

**Issue by firehand33** [merryjs/photo-viewer#78]
I getting the below warning after updated to version 3:

"Warning: Failed prop type: checker is not a function. (In 'checker(propValue, key, componentName, location, propFullName + '.' + key, ReactPropTypeSecret)', 'checker' is an instance of Object)"

Any idea how to fix this warning?

Version:
"@merryjs/photo-viewer": "^3.0.0",
"react-native": "^0.58.6",

**Comment by bang88** [comment]
Where the `checker` came from ?

**Comment by jvt** [comment]
I am also running into this exact issue. @firehand33 did you have any insight into where this `checker` prop is getting inserted?

**Comment by shahrajk** [comment]
Did you find any solution?
@firehand33 @jvt @bang88

**Comment by bang88** [comment]
@shahrajk I am sorry I think this issue not come from this lib. Please check your code and let me know.

**Comment by jvt** [comment]
I have traced this issue to specifically this line: https://github.com/merryjs/photo-viewer/blob/master/index.tsx#L78. The issue only occurs on iOS devices. Removing the iOS platform check to use `ImageSourcePropType` and instead forcing all platforms to use the manually-created `PropTypes.oneOfType` resolves the issue. @bang88 what is the reason that `ImageSourcePropType` is used only on iOS and not Android?

**Comment by bang88** [comment]
I can not tell more about this. If you find a solution for this please file a PR directly.

**Comment by jvt** [comment]
@bang88 What is the reason for the if statement [https://github.com/merryjs/photo-viewer/blob/master/index.tsx#L77](here)? The warning seems to go away when we use the `PropTypes.oneOfType` directly regardless of platform and no functionality appears to be broken.

**Comment by bang88** [comment]
Maybe its an old react-native issue.

**Comment by awartani** [comment]
having the same issue on iOS

**Comment by jvt** [comment]
@bang88 So if it functionally serves no purpose on modern react-native to have a different schema for iOS vs. Android, can we just get rid of that since it solves the issue? I've been using the `patch-package` npm package to apply this patch to my apps and the warning has disappeared and no adverse errors from the module have occurred.

**Comment by bang88** [comment]
@jvt Please send a PR directly.

**Comment by borisyankov** [comment]
The PropType `ImageSourcePropType` was moved to https://github.com/facebook/react-native/blob/master/Libraries/DeprecatedPropTypes/DeprecatedImageSourcePropType.js

**Comment by RodolfoGS** [comment]
Replace:
```
const ImageSourcePropType = require("react-native/Libraries/Image/ImageSourcePropType");
```

For:
```
const ImageSourcePropType = require("react-native/Libraries/DeprecatedPropTypes/DeprecatedImageSourcePropType");
```
