### ISSUE TITLE
Migrate to Android X

### ISSUE THREAD

**Issue by tmjordan** [merryjs/photo-viewer#87]
Hi, first thanks for that lib, it is very useful for me.
I want to suggest if we can update this lib to support android X. Many of react native libs support it at the moment, and this lib is incompatible with them without updating it to use Android X.
I'm not an expert on android development, so i can't make a PR to fix that problem. But i will be glad to help in any way.

**Comment by bang88** [comment]
PR are welcome.

There should have a upgrade guide in the official site.

**Comment by tmjordan** [comment]
@bang88 ok i will try to do it, and will make a PR if it works.
